- hosts: all

  gather_facts: true

  vars:
    WHISK_AUTH: 23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
    API_PORT: 31001

  tasks:
    - name: Set mycluster.yaml location
      set_fact:
        MYCLUSTER_YAML_PATH: /home/{{ ansible_user_id }}/openwhisk-deploy-kube/mycluster.yaml

    - name: Determine the right ip for AWS
      set_fact:
        API_HOST_NAME: "{{ ansible_ens5.ipv4.address }}"
      when: ansible_user_id == "ubuntu"

    - name: Determine the right ip for Vagrant
      set_fact:
        API_HOST_NAME: "{{ ansible_enp0s3.ipv4.address }}"
      when: ansible_user_id == "vagrant"

    - name: Generate mycluster.yaml
      template:
        src: mycluster.yaml.j2
        dest: "{{ MYCLUSTER_YAML_PATH }}"

    - name: Set environment variable WHISK_AUTH
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^WHISK_AUTH="
        line: "WHISK_AUTH={{ WHISK_AUTH }}"
      become: true

    - name: Set environment variable WHISK_SERVER
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^WHISK_SERVER="
        line: "WHISK_SERVER={{ API_HOST_NAME }}:{{ API_PORT }}"
      become: true

    - name: Configure OpenWhisk CLI
      shell: |
        wsk property set --auth {{ WHISK_AUTH }}
        wsk property set --apihost {{ API_HOST_NAME }}:{{ API_PORT }}

    - name:
      lineinfile:
        dest: "/home/{{ ansible_user_id }}/.bashrc"
        state: present
        regexp: "^alias wsk="
        line: "alias wsk='wsk -i'"
        create: true

